# Generated by Django 3.2.3 on 2021-07-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='light',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
